import type { Choice } from '../types/Choice';

export const regions: Choice[] = [
  { value: 'us-east-1', name: 'US East (N. Virginia)' },
  { value: 'us-east-2', name: 'US East (Ohio)' },
  { value: 'us-west-1', name: 'US West (N. California)' },
  { value: 'us-west-2', name: 'US West (Oregon)' },
  { value: 'af-south-1', name: 'Africa (Cape Town)' },
  { value: 'ap-east-1', name: 'Asia Pacific (Hong Kong)' },
  { value: 'ap-south-2', name: 'Asia Pacific (Hyderabad)' },
  { value: 'ap-southeast-3', name: 'Asia Pacific (Jakarta)' },
  { value: 'ap-southeast-5', name: 'Asia Pacific (Malaysia)' },
  { value: 'ap-southeast-4', name: 'Asia Pacific (Melbourne)' },
  { value: 'ap-south-1', name: 'Asia Pacific (Mumbai)' },
  { value: 'ap-northeast-3', name: 'Asia Pacific (Osaka)' },
  { value: 'ap-northeast-2', name: 'Asia Pacific (Seoul)' },
  { value: 'ap-southeast-1', name: 'Asia Pacific (Singapore)' },
  { value: 'ap-southeast-2', name: 'Asia Pacific (Sydney)' },
  { value: 'ap-northeast-1', name: 'Asia Pacific (Tokyo)' },
  { value: 'ca-central-1', name: 'Canada (Central)' },
  { value: 'ca-west-1', name: 'Canada West (Calgary)' },
  { value: 'cn-north-1', name: 'China (Beijing)' },
  { value: 'cn-northwest-1', name: 'China (Ningxia)' },
  { value: 'eu-central-1', name: 'Europe (Frankfurt)' },
  { value: 'eu-west-1', name: 'Europe (Ireland)' },
  { value: 'eu-west-2', name: 'Europe (London)' },
  { value: 'eu-south-1', name: 'Europe (Milan)' },
  { value: 'eu-west-3', name: 'Europe (Paris)' },
  { value: 'eu-south-2', name: 'Europe (Spain)' },
  { value: 'eu-north-1', name: 'Europe (Stockholm)' },
  { value: 'eu-central-2', name: 'Europe (Zurich)' },
  { value: 'il-central-1', name: 'Israel (Tel Aviv)' },
  { value: 'me-south-1', name: 'Middle East (Bahrain)' },
  { value: 'me-central-1', name: 'Middle East (UAE)' },
  { value: 'sa-east-1', name: 'South America (São Paulo)' },
];
